name: Process PR Data
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 2: Get PR Description
      - name: Extract PR Description
        id: pr-description
        run: |
          echo "DESCRIPTION<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.pull_request.body || '[No description]' }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Step 3: Fetch URL Contents
      - name: Fetch URL Data
        id: fetch-url
        run: |
          curl https://personalprojects-882101cf.mintlify.app/READMES/mintlify-gh-action-poc > output.html
          echo "FILEPATH=output.html" >> $GITHUB_OUTPUT

      # Step 4: Build and run Docker container
      - name: Build and run Docker container
        run: |
          docker build -t llm-compare .
          docker run --privileged \
            llm-compare \
            "${{ steps.pr-description.outputs.DESCRIPTION }}" \
            "${{ steps.fetch-url.outputs.FILEPATH }}"
